### PR TITLE
Cleanup tags on applications

### PR DESCRIPTION
**Pull request by dodecatheon**
Clean up tags on applications

### CODE REVIEW

**Review by douglasjacobsen — CHANGES_REQUESTED** [review]
We discussed this in one of our internal meetings.

I don't feel like this goes quite far enough at minimizing redundant tags, but also we need to decide how we want to deal with things like the `hcls` and `life-sciences` tags.

**Comment by dodecatheon** [comment]
> We discussed this in one of our internal meetings.
> 
> I don't feel like this goes quite far enough at minimizing redundant tags, but also we need to decide how we want to deal with things like the `hcls` and `life-sciences` tags.

Good point. They could easily be added on non-public application repos if needed, as you said. Shall I remove them?

**Comment by douglasjacobsen** [comment]
I think we should discuss this in our meeting tomorrow, and decide what we want to do with the tags moving forward.

**Comment by douglasjacobsen** [comment]
Given the discussion we had a while ago, I'm going to close this PR.

**Pull request closed without merging**
